
import { Product, Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  TR: {
    welcome: "Hoş Geldiniz",
    discoverMenu: "Menüyü Keşfet",
    pricingPlans: "Abonelik Paketleri",
    tableNo: "Masa Numarası",
    selectTable: "Masa Seçiniz",
    nameOptional: "Adınız",
    selectLanguage: "Dil Seçin",
    search: "Ara...",
    cart: "Sepetim",
    total: "Toplam",
    confirmOrder: "Siparişi Onayla",
    orderNote: "Sipariş Notu",
    emptyCart: "Sepetiniz henüz boş.",
    orderTracking: "Sipariş Takibi",
    statusReceived: "Sipariş Alındı",
    statusPreparing: "Hazırlanıyor",
    statusServed: "Servis Edildi",
    callWaiter: "Garson Çağır",
    requestCheck: "Hesap İste",
    upsellTitle: "Harika Bir Seçim!",
    upsellDesc: "Yanına bunları da denemek ister misiniz?",
    maybeLater: "Belki daha sonra",
    recommendation: "Günün Tavsiyesi",
    chefsSpecial: "Şefin Spesiyali",
    specialNote: "Sadece bugün için hazırlanan özel lezzet.",
    back: "Geri",
    items: "Ürün",
    orderSent: "Siparişiniz mutfağa iletildi!",
    waiterCalled: "Garson çağrıldı.",
    checkRequested: "Hesap talebi iletildi.",
    kitchenMessage: "Mutfaktan Mesaj",
    staffAccess: "Personel Girişi",
    attribution: "Bu uygulama Cevikhan Grafik Design tarafından geliştirilmiştir.",
    subscriptionTitle: "Süre Doldu",
    subscriptionDesc: "Hizmet süreniz sona ermiştir. Devam etmek için lütfen aboneliğinizi yenileyin.",
    monthlyPlan: "Aylık Abonelik",
    yearlyPlan: "Yıllık Abonelik",
    payWithStripe: "Stripe ile Öde",
    payWithPaypal: "PayPal ile Öde",
    close: "Kapat",
    categories: {
      all: "Hepsi",
      haehnchen: "Tavuk",
      burger: "Burger",
      pasta: "Makarna",
      salat: "Salata",
      dessert: "Tatlı",
      drinks: "İçecek"
    }
  },
  EN: {
    welcome: "Welcome",
    discoverMenu: "Discover Menu",
    pricingPlans: "Subscription Plans",
    tableNo: "Table Number",
    selectTable: "Select Table",
    nameOptional: "Your Name",
    selectLanguage: "Select Language",
    search: "Search...",
    cart: "My Cart",
    total: "Total",
    confirmOrder: "Confirm Order",
    orderNote: "Order Note",
    emptyCart: "Your cart is empty.",
    orderTracking: "Order Tracking",
    statusReceived: "Order Received",
    statusPreparing: "Preparing",
    statusServed: "Served",
    callWaiter: "Call Waiter",
    requestCheck: "Request Check",
    upsellTitle: "Great Choice!",
    upsellDesc: "Would you like to try these as well?",
    maybeLater: "Maybe later",
    recommendation: "Recommendation of the Day",
    chefsSpecial: "Chef's Special",
    specialNote: "Special flavor prepared for today only.",
    back: "Back",
    items: "Items",
    orderSent: "Order sent to kitchen!",
    waiterCalled: "Waiter called.",
    checkRequested: "Check requested.",
    kitchenMessage: "Message from Kitchen",
    staffAccess: "Staff Login",
    attribution: "This application was developed by Cevikhan Grafik Design.",
    subscriptionTitle: "Time's Up",
    subscriptionDesc: "Your service period has expired. Please renew your subscription to continue.",
    monthlyPlan: "Monthly Subscription",
    yearlyPlan: "Yearly Subscription",
    payWithStripe: "Pay with Stripe",
    payWithPaypal: "Pay with PayPal",
    close: "Close",
    categories: {
      all: "All",
      haehnchen: "Chicken",
      burger: "Burger",
      pasta: "Pasta",
      salat: "Salad",
      dessert: "Dessert",
      drinks: "Drinks"
    }
  },
  DE: {
    welcome: "Willkommen",
    discoverMenu: "Menü Entdecken",
    pricingPlans: "Abonnement-Pläne",
    tableNo: "Tischnummer",
    selectTable: "Tisch wählen",
    nameOptional: "Ihr Name",
    selectLanguage: "Sprache wählen",
    search: "Suchen...",
    cart: "Mein Warenkorb",
    total: "Gesamt",
    confirmOrder: "Bestellung bestätigen",
    orderNote: "Bestellnotiz",
    emptyCart: "Ihr Warenkorb ist leer.",
    orderTracking: "Bestellverfolgung",
    statusReceived: "Eingegangen",
    statusPreparing: "Wird zubereitet",
    statusServed: "Serviert",
    callWaiter: "Kellner rufen",
    requestCheck: "Rechnung anfordern",
    upsellTitle: "Gute Wahl!",
    upsellDesc: "Möchten Sie das dazu probieren?",
    maybeLater: "Vielleicht später",
    recommendation: "Empfehlung des Tages",
    chefsSpecial: "Empfehlung des Chefs",
    specialNote: "Spezielles Aroma, nur heute zubereitet.",
    back: "Zurück",
    items: "Produkte",
    orderSent: "Bestellung an Küche gesendet!",
    waiterCalled: "Kellner gerufen.",
    checkRequested: "Rechnung angefordert.",
    kitchenMessage: "Nachricht aus der Küche",
    staffAccess: "Personalanmeldung",
    attribution: "Diese Anwendung wurde von Cevikhan Grafik Design entwickelt.",
    subscriptionTitle: "Zeit abgelaufen",
    subscriptionDesc: "Ihre Servicezeit ist abgelaufen. Bitte erneuern Sie Ihr Abonnement.",
    monthlyPlan: "Monatsabo",
    yearlyPlan: "Jahresabo",
    payWithStripe: "Mit Stripe bezahlen",
    payWithPaypal: "Mit PayPal bezahlen",
    close: "Schließen",
    categories: {
      all: "Alle",
      haehnchen: "Hähnchen",
      burger: "Burger",
      pasta: "Pasta",
      salat: "Salad",
      dessert: "Nachtisch",
      drinks: "Getränke"
    }
  },
  RU: {
    welcome: "Добро пожаловать",
    discoverMenu: "Открыть меню",
    pricingPlans: "Планы подписки",
    tableNo: "Номер стола",
    selectTable: "Выберите стол",
    nameOptional: "Ваше имя",
    selectLanguage: "Выберите язык",
    search: "Поиск...",
    cart: "Моя корзина",
    total: "Итого",
    confirmOrder: "Подтвердить заказ",
    orderNote: "Комментарий",
    emptyCart: "Ваша корзина пуста.",
    orderTracking: "Отслеживание заказа",
    statusReceived: "Заказ получен",
    statusPreparing: "Готовится",
    statusServed: "Подано",
    callWaiter: "Вызвать официанта",
    requestCheck: "Запросить счет",
    upsellTitle: "Отличный выбор!",
    upsellDesc: "Хотите попробовать это тоже?",
    maybeLater: "Может быть позже",
    recommendation: "Рекомендация дня",
    chefsSpecial: "Особое блюдо от шефа",
    specialNote: "Особый вкус, приготовленный только сегодня.",
    back: "Назад",
    items: "Товары",
    orderSent: "Заказ отправлен на кухню!",
    waiterCalled: "Официант вызван.",
    checkRequested: "Счет запрошен.",
    kitchenMessage: "Сообщение от кухни",
    staffAccess: "Вход для персонала",
    attribution: "Это приложение разработано Cevikhan Grafik Design.",
    subscriptionTitle: "Время вышло",
    subscriptionDesc: "Срок обслуживания истек. Пожалуйста, продлите подписку.",
    monthlyPlan: "Месячная подписка",
    yearlyPlan: "Годовая подписка",
    payWithStripe: "Оплатить через Stripe",
    payWithPaypal: "Оплатить через PayPal",
    close: "Закрыть",
    categories: {
      all: "Все",
      haehnchen: "Курица",
      burger: "Бургер",
      pasta: "Паста",
      salat: "Салат",
      dessert: "Десерт",
      drinks: "Напитки"
    }
  },
  AR: {
    welcome: "أهلاً بك",
    discoverMenu: "اكتشف القائمة",
    pricingPlans: "خطط الاشتراك",
    tableNo: "رقم الطاولة",
    selectTable: "اختر الطاولة",
    nameOptional: "اسمك",
    selectLanguage: "اختر اللغة",
    search: "بحث...",
    cart: "سلتي",
    total: "المجموع",
    confirmOrder: "تأكيد الطلب",
    orderNote: "ملاحظة الطلب",
    emptyCart: "سلتك فارغة حالياً.",
    orderTracking: "تتبع الطلب",
    statusReceived: "تم استلام الطلب",
    statusPreparing: "قيد التحضير",
    statusServed: "تم التقديم",
    callWaiter: "نداء النادل",
    requestCheck: "طلب الفاتورة",
    upsellTitle: "اختيار رائع!",
    upsellDesc: "هل تود تجربة هذه أيضاً؟",
    maybeLater: "ربما لاحقاً",
    recommendation: "توصية اليوم",
    chefsSpecial: "تخصص الشيف",
    specialNote: "نكهة خاصة محضرة لهذا اليوم فقط.",
    back: "عودة",
    items: "أصناف",
    orderSent: "تم إرسال الطلب للمطبخ!",
    waiterCalled: "تم نداء النادل.",
    checkRequested: "تم طلب الفاتورة.",
    kitchenMessage: "رسالة من المطبخ",
    staffAccess: "دخول الموظفين",
    attribution: "تم تطوير هذا التطبيق بواسطة Cevikhan Grafik Design.",
    subscriptionTitle: "انتهى الوقت",
    subscriptionDesc: "انتهت فترة الخدمة الخاصة بك. يرجى تجديد الاشتراك للمتابعة.",
    monthlyPlan: "اشتراك شهري",
    yearlyPlan: "اشتراك سنوي",
    payWithStripe: "الدفع عبر Stripe",
    payWithPaypal: "الدفع عبر PayPal",
    close: "إغلاق",
    categories: {
      all: "الكل",
      haehnchen: "دجاج",
      burger: "برجر",
      pasta: "باستا",
      salat: "سلطة",
      dessert: "حلويات",
      drinks: "مشروبات"
    }
  },
  IT: {
    welcome: "Benvenuti",
    discoverMenu: "Scopri il Menù",
    pricingPlans: "Piani di Abbonamento",
    tableNo: "Numero del Tavolo",
    selectTable: "Seleziona Tavolo",
    nameOptional: "Il tuo nome",
    selectLanguage: "Scegli Lingua",
    search: "Cerca...",
    cart: "Il mio Carrello",
    total: "Totale",
    confirmOrder: "Conferma Ordine",
    orderNote: "Nota per l'ordine",
    emptyCart: "Il tuo carrello è vuoto.",
    orderTracking: "Tracciamento Ordine",
    statusReceived: "Ordine Ricevuto",
    statusPreparing: "In preparazione",
    statusServed: "Servito",
    callWaiter: "Chiama Cameriere",
    requestCheck: "Richiedi Conto",
    upsellTitle: "Ottima scelta!",
    upsellDesc: "Vorresti provare anche questi?",
    maybeLater: "Forse più tardi",
    recommendation: "Consigliato del giorno",
    chefsSpecial: "Specialità dello Chef",
    specialNote: "Sapore speciale preparato solo per oggi.",
    back: "Indietro",
    items: "Articoli",
    orderSent: "Ordine inviato in cucina!",
    waiterCalled: "Cameriere chiamato.",
    checkRequested: "Conto richiesto.",
    kitchenMessage: "Messaggio dalla cucina",
    staffAccess: "Accesso Personale",
    attribution: "Questa applicazione è stata sviluppata da Cevikhan Grafik Design.",
    subscriptionTitle: "Tempo scaduto",
    subscriptionDesc: "Il tuo periodo di servizio è scaduto. Rinnova l'abbonamento per continuare.",
    monthlyPlan: "Abbonamento mensile",
    yearlyPlan: "Abbonamento annuale",
    payWithStripe: "Paga con Stripe",
    payWithPaypal: "Paga con PayPal",
    close: "Chiudi",
    categories: {
      all: "Tutti",
      haehnchen: "Pollo",
      burger: "Burger",
      pasta: "Pasta",
      salat: "Insalata",
      dessert: "Dolci",
      drinks: "Bevande"
    }
  },
  FR: {
    welcome: "Bienvenue",
    discoverMenu: "Découvrir le Menu",
    pricingPlans: "Plans d'Abonnement",
    tableNo: "Numéro de Table",
    selectTable: "Choisir Table",
    nameOptional: "Votre Nom",
    selectLanguage: "Choisir Langue",
    search: "Rechercher...",
    cart: "Mon Panier",
    total: "Total",
    confirmOrder: "Confirmer Commande",
    orderNote: "Note de commande",
    emptyCart: "Votre panier est vide.",
    orderTracking: "Suivi de Commande",
    statusReceived: "Commande Reçue",
    statusPreparing: "En préparation",
    statusServed: "Servi",
    callWaiter: "Appeler Serveur",
    requestCheck: "Demander l'Addition",
    upsellTitle: "Excellent choix !",
    upsellDesc: "Souhaitez-vous aussi essayer ceux-ci ?",
    maybeLater: "Peut-être plus tard",
    recommendation: "Recommandation du jour",
    chefsSpecial: "Spécialité du Chef",
    specialNote: "Saveur spéciale préparée uniquement pour aujourd'hui.",
    back: "Retour",
    items: "Articles",
    orderSent: "Commande envoyée en cuisine !",
    waiterCalled: "Serveur appelé.",
    checkRequested: "Addition demandée.",
    kitchenMessage: "Message de la Cuisine",
    staffAccess: "Accès Personnel",
    attribution: "Cette application a été développée par Cevikhan Grafik Design.",
    subscriptionTitle: "Temps écoulé",
    subscriptionDesc: "Votre période de service a expiré. Veuillez renouveler votre abonnement.",
    monthlyPlan: "Abonnement mensuel",
    yearlyPlan: "Abonnement annuel",
    payWithStripe: "Payer avec Stripe",
    payWithPaypal: "Payer avec PayPal",
    close: "Fermer",
    categories: {
      all: "Tous",
      haehnchen: "Poulet",
      burger: "Burger",
      pasta: "Pâtes",
      salat: "Salade",
      dessert: "Dessert",
      drinks: "Boissons"
    }
  }
};

export const CATEGORIES = [
  { id: 'all', icon: '🍽️' },
  { id: 'haehnchen', icon: '🍗' },
  { id: 'burger', icon: '🍔' },
  { id: 'pasta', icon: '🍝' },
  { id: 'salat', icon: '🥗' },
  { id: 'dessert', icon: '🍰' },
  { id: 'drinks', icon: '🥤' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Curry Hähnchen',
    description: 'Zartes Hähnchenfilet in einer cremigen Currysauce, serviert mit Reis und Salat.',
    price: 11.90,
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=400',
    category: 'haehnchen',
    allergens: ['Laktose'],
    spiceLevel: 1,
    upsellItems: ['p7'],
    available: true
  },
  {
    id: 'p2',
    name: 'Cheeseburger Deluxe',
    description: '180g Rindfleisch, Cheddar Käse, Salat, Tomaten, Gewürzgurken, rote Zwiebeln.',
    price: 8.90,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=400',
    category: 'burger',
    allergens: ['Gluten', 'Laktose'],
    spiceLevel: 0,
    upsellItems: ['p7', 'p8'],
    available: true
  },
  {
    id: 'p3',
    name: 'Penne Arrabiata',
    description: 'Scharfe Tomatensauce mit Knoblauch, Chili und frischem Basilikum.',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1626844131082-256783844137?auto=format&fit=crop&q=80&w=400',
    category: 'pasta',
    allergens: ['Gluten'],
    spiceLevel: 2,
    upsellItems: ['p8'],
    available: true
  },
  {
    id: 'p4',
    name: 'Caesar Salad',
    description: 'Römersalat, Croûtons, Parmesan, Hähnchenbruststreifen und Caesar-Dressing.',
    price: 10.50,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&q=80&w=400',
    category: 'salat',
    allergens: ['Laktose', 'Gluten', 'Ei'],
    spiceLevel: 0,
    upsellItems: ['p7'],
    available: true
  },
  {
    id: 'p5',
    name: 'Tiramisu',
    description: 'Klassisches italienisches Dessert mit Mascarpone, Löffelbiskuits und Espresso.',
    price: 5.90,
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?auto=format&fit=crop&q=80&w=400',
    category: 'dessert',
    allergens: ['Laktose', 'Gluten', 'Ei'],
    spiceLevel: 0,
    upsellItems: ['p6'],
    available: true
  },
  {
    id: 'p6',
    name: 'Espresso',
    description: 'Starker, aromatischer italienischer Kaffee.',
    price: 2.50,
    image: 'https://images.unsplash.com/photo-1610889556283-ddf54970f4a9?auto=format&fit=crop&q=80&w=400',
    category: 'drinks',
    allergens: [],
    spiceLevel: 0,
    upsellItems: [],
    available: true
  },
  {
    id: 'p7',
    name: 'Cola Zero 0.33l',
    description: 'Erfrischendes koffeinhaltiges Getränk ohne Zucker.',
    price: 2.90,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=400',
    category: 'drinks',
    allergens: [],
    spiceLevel: 0,
    upsellItems: [],
    available: true
  },
  {
    id: 'p8',
    name: 'Hausgemachte Limonade',
    description: 'Frische Zitrone, Minze und Holundersirup.',
    price: 4.50,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400',
    category: 'drinks',
    allergens: [],
    spiceLevel: 0,
    upsellItems: [],
    available: true
  }
];
